DROP TABLE IF EXISTS `Groups`;
CREATE TABLE `Groups` (
	`group_id` INT(64) NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(128) NOT NULL UNIQUE DEFAULT '',
	PRIMARY KEY (`group_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
